a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
add=(a+b)
sub=(a-b)
div=(b/a)
multi=(a*b)
print(add)
print(sub)
print(div)
print(multi)
print ("add=10")
print("sub=2")
print("div=0")
print("multi=24")